# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Temp/sa2-final/SA2_final_project/SA2_final_project.srcs/sources_1/bd/final_proj/ip/final_proj_xadc_wiz_0_1/final_proj_xadc_wiz_0_1.xci
# IP: The module: 'final_proj_xadc_wiz_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Temp/sa2-final/SA2_final_project/SA2_final_project.srcs/sources_1/bd/final_proj/ip/final_proj_xadc_wiz_0_1/final_proj_xadc_wiz_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'final_proj_xadc_wiz_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Temp/sa2-final/SA2_final_project/SA2_final_project.srcs/sources_1/bd/final_proj/ip/final_proj_xadc_wiz_0_1/final_proj_xadc_wiz_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'final_proj_xadc_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Temp/sa2-final/SA2_final_project/SA2_final_project.srcs/sources_1/bd/final_proj/ip/final_proj_xadc_wiz_0_1/final_proj_xadc_wiz_0_1.xci
# IP: The module: 'final_proj_xadc_wiz_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Temp/sa2-final/SA2_final_project/SA2_final_project.srcs/sources_1/bd/final_proj/ip/final_proj_xadc_wiz_0_1/final_proj_xadc_wiz_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'final_proj_xadc_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Temp/sa2-final/SA2_final_project/SA2_final_project.srcs/sources_1/bd/final_proj/ip/final_proj_xadc_wiz_0_1/final_proj_xadc_wiz_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'final_proj_xadc_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
