# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Temp/sa2-final/SA2_final_project/SA2_final_project.srcs/sources_1/bd/final_proj/ip/final_proj_system_ila_0_3/final_proj_system_ila_0_3.xci
# IP: The module: 'final_proj_system_ila_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Temp/sa2-final/SA2_final_project/SA2_final_project.srcs/sources_1/bd/final_proj/ip/final_proj_system_ila_0_3/bd_0/bd_e91c.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e91c || ORIG_REF_NAME==bd_e91c} -quiet] -quiet

# IP: c:/Temp/sa2-final/SA2_final_project/SA2_final_project.srcs/sources_1/bd/final_proj/ip/final_proj_system_ila_0_3/bd_0/ip/ip_0/bd_e91c_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e91c_ila_lib_0 || ORIG_REF_NAME==bd_e91c_ila_lib_0} -quiet] -quiet

# IP: c:/Temp/sa2-final/SA2_final_project/SA2_final_project.srcs/sources_1/bd/final_proj/ip/final_proj_system_ila_0_3/bd_0/ip/ip_1/bd_e91c_g_inst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e91c_g_inst_0 || ORIG_REF_NAME==bd_e91c_g_inst_0} -quiet] -quiet

# IP: c:/Temp/sa2-final/SA2_final_project/SA2_final_project.srcs/sources_1/bd/final_proj/ip/final_proj_system_ila_0_3/bd_0/ip/ip_2/bd_e91c_slot_0_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e91c_slot_0_aw_0 || ORIG_REF_NAME==bd_e91c_slot_0_aw_0} -quiet] -quiet

# IP: c:/Temp/sa2-final/SA2_final_project/SA2_final_project.srcs/sources_1/bd/final_proj/ip/final_proj_system_ila_0_3/bd_0/ip/ip_3/bd_e91c_slot_0_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e91c_slot_0_w_0 || ORIG_REF_NAME==bd_e91c_slot_0_w_0} -quiet] -quiet

# IP: c:/Temp/sa2-final/SA2_final_project/SA2_final_project.srcs/sources_1/bd/final_proj/ip/final_proj_system_ila_0_3/bd_0/ip/ip_4/bd_e91c_slot_0_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e91c_slot_0_b_0 || ORIG_REF_NAME==bd_e91c_slot_0_b_0} -quiet] -quiet

# IP: c:/Temp/sa2-final/SA2_final_project/SA2_final_project.srcs/sources_1/bd/final_proj/ip/final_proj_system_ila_0_3/bd_0/ip/ip_5/bd_e91c_slot_0_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e91c_slot_0_ar_0 || ORIG_REF_NAME==bd_e91c_slot_0_ar_0} -quiet] -quiet

# IP: c:/Temp/sa2-final/SA2_final_project/SA2_final_project.srcs/sources_1/bd/final_proj/ip/final_proj_system_ila_0_3/bd_0/ip/ip_6/bd_e91c_slot_0_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e91c_slot_0_r_0 || ORIG_REF_NAME==bd_e91c_slot_0_r_0} -quiet] -quiet

# XDC: c:/Temp/sa2-final/SA2_final_project/SA2_final_project.srcs/sources_1/bd/final_proj/ip/final_proj_system_ila_0_3/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_e91c_ila_lib_0 || ORIG_REF_NAME==bd_e91c_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Temp/sa2-final/SA2_final_project/SA2_final_project.srcs/sources_1/bd/final_proj/ip/final_proj_system_ila_0_3/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_e91c_ila_lib_0 || ORIG_REF_NAME==bd_e91c_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Temp/sa2-final/SA2_final_project/SA2_final_project.srcs/sources_1/bd/final_proj/ip/final_proj_system_ila_0_3/bd_0/ip/ip_0/bd_e91c_ila_lib_0_ooc.xdc

# XDC: c:/Temp/sa2-final/SA2_final_project/SA2_final_project.srcs/sources_1/bd/final_proj/ip/final_proj_system_ila_0_3/bd_0/bd_e91c_ooc.xdc

# XDC: c:/Temp/sa2-final/SA2_final_project/SA2_final_project.srcs/sources_1/bd/final_proj/ip/final_proj_system_ila_0_3/final_proj_system_ila_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'final_proj_system_ila_0_3'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Temp/sa2-final/SA2_final_project/SA2_final_project.srcs/sources_1/bd/final_proj/ip/final_proj_system_ila_0_3/final_proj_system_ila_0_3.xci
# IP: The module: 'final_proj_system_ila_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Temp/sa2-final/SA2_final_project/SA2_final_project.srcs/sources_1/bd/final_proj/ip/final_proj_system_ila_0_3/bd_0/bd_e91c.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e91c || ORIG_REF_NAME==bd_e91c} -quiet] -quiet

# IP: c:/Temp/sa2-final/SA2_final_project/SA2_final_project.srcs/sources_1/bd/final_proj/ip/final_proj_system_ila_0_3/bd_0/ip/ip_0/bd_e91c_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e91c_ila_lib_0 || ORIG_REF_NAME==bd_e91c_ila_lib_0} -quiet] -quiet

# IP: c:/Temp/sa2-final/SA2_final_project/SA2_final_project.srcs/sources_1/bd/final_proj/ip/final_proj_system_ila_0_3/bd_0/ip/ip_1/bd_e91c_g_inst_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e91c_g_inst_0 || ORIG_REF_NAME==bd_e91c_g_inst_0} -quiet] -quiet

# IP: c:/Temp/sa2-final/SA2_final_project/SA2_final_project.srcs/sources_1/bd/final_proj/ip/final_proj_system_ila_0_3/bd_0/ip/ip_2/bd_e91c_slot_0_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e91c_slot_0_aw_0 || ORIG_REF_NAME==bd_e91c_slot_0_aw_0} -quiet] -quiet

# IP: c:/Temp/sa2-final/SA2_final_project/SA2_final_project.srcs/sources_1/bd/final_proj/ip/final_proj_system_ila_0_3/bd_0/ip/ip_3/bd_e91c_slot_0_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e91c_slot_0_w_0 || ORIG_REF_NAME==bd_e91c_slot_0_w_0} -quiet] -quiet

# IP: c:/Temp/sa2-final/SA2_final_project/SA2_final_project.srcs/sources_1/bd/final_proj/ip/final_proj_system_ila_0_3/bd_0/ip/ip_4/bd_e91c_slot_0_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e91c_slot_0_b_0 || ORIG_REF_NAME==bd_e91c_slot_0_b_0} -quiet] -quiet

# IP: c:/Temp/sa2-final/SA2_final_project/SA2_final_project.srcs/sources_1/bd/final_proj/ip/final_proj_system_ila_0_3/bd_0/ip/ip_5/bd_e91c_slot_0_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e91c_slot_0_ar_0 || ORIG_REF_NAME==bd_e91c_slot_0_ar_0} -quiet] -quiet

# IP: c:/Temp/sa2-final/SA2_final_project/SA2_final_project.srcs/sources_1/bd/final_proj/ip/final_proj_system_ila_0_3/bd_0/ip/ip_6/bd_e91c_slot_0_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e91c_slot_0_r_0 || ORIG_REF_NAME==bd_e91c_slot_0_r_0} -quiet] -quiet

# XDC: c:/Temp/sa2-final/SA2_final_project/SA2_final_project.srcs/sources_1/bd/final_proj/ip/final_proj_system_ila_0_3/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_e91c_ila_lib_0 || ORIG_REF_NAME==bd_e91c_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Temp/sa2-final/SA2_final_project/SA2_final_project.srcs/sources_1/bd/final_proj/ip/final_proj_system_ila_0_3/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_e91c_ila_lib_0 || ORIG_REF_NAME==bd_e91c_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Temp/sa2-final/SA2_final_project/SA2_final_project.srcs/sources_1/bd/final_proj/ip/final_proj_system_ila_0_3/bd_0/ip/ip_0/bd_e91c_ila_lib_0_ooc.xdc

# XDC: c:/Temp/sa2-final/SA2_final_project/SA2_final_project.srcs/sources_1/bd/final_proj/ip/final_proj_system_ila_0_3/bd_0/bd_e91c_ooc.xdc

# XDC: c:/Temp/sa2-final/SA2_final_project/SA2_final_project.srcs/sources_1/bd/final_proj/ip/final_proj_system_ila_0_3/final_proj_system_ila_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'final_proj_system_ila_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
