#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Apr 16 23:16:18 CDT 2026
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim final_proj_wrapper_behav -key {Behavioral:sim_1:Functional:final_proj_wrapper} -tclbatch final_proj_wrapper.tcl -protoinst "protoinst_files/final_proj.protoinst" -log simulate.log"
xsim final_proj_wrapper_behav -key {Behavioral:sim_1:Functional:final_proj_wrapper} -tclbatch final_proj_wrapper.tcl -protoinst "protoinst_files/final_proj.protoinst" -log simulate.log

