# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/zedboard.xdc

# Block Designs: bd/final_proj/final_proj.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==final_proj || ORIG_REF_NAME==final_proj} -quiet] -quiet

# IP: bd/final_proj/ip/final_proj_processing_system7_0_0/final_proj_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==final_proj_processing_system7_0_0 || ORIG_REF_NAME==final_proj_processing_system7_0_0} -quiet] -quiet

# IP: bd/final_proj/ip/final_proj_axi_gpio_0_0/final_proj_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==final_proj_axi_gpio_0_0 || ORIG_REF_NAME==final_proj_axi_gpio_0_0} -quiet] -quiet

# IP: bd/final_proj/ip/final_proj_axi_gpio_0_1/final_proj_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==final_proj_axi_gpio_0_1 || ORIG_REF_NAME==final_proj_axi_gpio_0_1} -quiet] -quiet

# IP: bd/final_proj/ip/final_proj_axi_gpio_0_2/final_proj_axi_gpio_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==final_proj_axi_gpio_0_2 || ORIG_REF_NAME==final_proj_axi_gpio_0_2} -quiet] -quiet

# IP: bd/final_proj/ip/final_proj_xbar_0/final_proj_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==final_proj_xbar_0 || ORIG_REF_NAME==final_proj_xbar_0} -quiet] -quiet

# IP: bd/final_proj/ip/final_proj_ps7_0_axi_periph_0/final_proj_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==final_proj_ps7_0_axi_periph_0 || ORIG_REF_NAME==final_proj_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/final_proj/ip/final_proj_rst_ps7_0_100M_0/final_proj_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==final_proj_rst_ps7_0_100M_0 || ORIG_REF_NAME==final_proj_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/final_proj/ip/final_proj_xadc_wiz_0_1/final_proj_xadc_wiz_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==final_proj_xadc_wiz_0_1 || ORIG_REF_NAME==final_proj_xadc_wiz_0_1} -quiet] -quiet

# IP: bd/final_proj/ip/final_proj_system_ila_0_0/final_proj_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==final_proj_system_ila_0_0 || ORIG_REF_NAME==final_proj_system_ila_0_0} -quiet] -quiet

# IP: bd/final_proj/ip/final_proj_xlconstant_0_0/final_proj_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==final_proj_xlconstant_0_0 || ORIG_REF_NAME==final_proj_xlconstant_0_0} -quiet] -quiet

# IP: bd/final_proj/ip/final_proj_analog_channel_fr_0_2/final_proj_analog_channel_fr_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==final_proj_analog_channel_fr_0_2 || ORIG_REF_NAME==final_proj_analog_channel_fr_0_2} -quiet] -quiet

# IP: bd/final_proj/ip/final_proj_auto_pc_0/final_proj_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==final_proj_auto_pc_0 || ORIG_REF_NAME==final_proj_auto_pc_0} -quiet] -quiet

# XDC: bd/final_proj/final_proj_ooc.xdc
